// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/ArtisanChocolatePortfolio-1i1rv4/App.tsx": () => import("../components/mockups/templates/ArtisanChocolatePortfolio-1i1rv4/App.tsx"),
  "./components/mockups/templates/ArtisanChocolatePortfolio-3063yw/App.tsx": () => import("../components/mockups/templates/ArtisanChocolatePortfolio-3063yw/App.tsx"),
  "./components/mockups/templates/ArtDecoNurseryLandingPage-rb7TjH/App.tsx": () => import("../components/mockups/templates/ArtDecoNurseryLandingPage-rb7TjH/App.tsx"),
  "./components/mockups/templates/ArtisanChocolatePortfolio-k3iXcf/App.tsx": () => import("../components/mockups/templates/ArtisanChocolatePortfolio-k3iXcf/App.tsx"),
  "./components/mockups/templates/BlueCoworkingLanding-WiM25K/Atrium.tsx": () => import("../components/mockups/templates/BlueCoworkingLanding-WiM25K/Atrium.tsx"),
  "./components/mockups/templates/EditorialEVClinicLandingPage-eyARC7/App.tsx": () => import("../components/mockups/templates/EditorialEVClinicLandingPage-eyARC7/App.tsx"),
  "./components/mockups/templates/EditorialLanguageHiringPage-xfl0Tj/App.tsx": () => import("../components/mockups/templates/EditorialLanguageHiringPage-xfl0Tj/App.tsx"),
  "./components/mockups/templates/SunsetGridPricingBoard-tTrbAa/App.tsx": () => import("../components/mockups/templates/SunsetGridPricingBoard-tTrbAa/App.tsx"),
  "./components/mockups/templates/SwissBreathworkLandingPage-uyqfVx/App.tsx": () => import("../components/mockups/templates/SwissBreathworkLandingPage-uyqfVx/App.tsx"),
  "./components/mockups/templates/WarmClinicFundraiserLandingPage-YIw3IT/App.tsx": () => import("../components/mockups/templates/WarmClinicFundraiserLandingPage-YIw3IT/App.tsx")
};
