// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/BlueCoworkingLanding-WiM25K/Atrium.tsx": () => import("../components/mockups/templates/BlueCoworkingLanding-WiM25K/Atrium.tsx"),
  "./components/mockups/templates/EditorialEVClinicLandingPage-eyARC7/App.tsx": () => import("../components/mockups/templates/EditorialEVClinicLandingPage-eyARC7/App.tsx"),
  "./components/mockups/templates/EditorialLanguageHiringPage-xfl0Tj/App.tsx": () => import("../components/mockups/templates/EditorialLanguageHiringPage-xfl0Tj/App.tsx")
};
